<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1545639544755" stop="1545639544880">
  <name>test_login</name>
  <labels/>
  <test-cases>
    <test-case start="1545639544755" status="passed" stop="1545639544755">
      <name>TestLogin.test_a</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="9080-MainThread"/>
        <label name="host" value="zhuwei-PC"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1545639544755" status="failed" stop="1545639544880">
      <name>TestLogin.test_b</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;test_login.TestLogin object at 0x0324B210&gt;

    @allure.step('测试登录的步骤')
    def test_b(self):
        print("\n2222")
        allure.attach('描述1','请输入用户名')
        print("\n3333")
        allure.attach('描述2','请输入用户密码')
&gt;       assert 0
E       assert 0

test_login.py:16: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="9080-MainThread"/>
        <label name="host" value="zhuwei-PC"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps>
        <step start="1545639544755" status="failed" stop="1545639544770">
          <name>测试登录的步骤</name>
          <title>测试登录的步骤</title>
          <attachments>
            <attachment source="804b40da-def7-4d96-97d8-e361d2e7073b-attachment.txt" title="描述1" type="text/plain"/>
            <attachment source="b82069e3-d87f-4970-9786-505868a9d007-attachment.txt" title="描述2" type="text/plain"/>
          </attachments>
          <steps/>
        </step>
      </steps>
    </test-case>
  </test-cases>
</ns0:test-suite>
